apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: b2b-db-secret
  namespace: b2bi-prod
spec:
  encryptedData:
    DB_PASSWORD: AgAOMKy2FsFfB9ZOuslYdom6L0M7v63RcJtNvbvbTFYT+pAp2juW+SL1RlAuBTZtFP7XFBaAjaFMKaMuReebU4ke2sv/TODP8DScjM+i0bBLJTJ2nn1B1rs3YouqcoOby2YXlOelk5dTwTbYP0AUVBRPqkEiwWhTduKZdZkSyO4ZjZIxtw/uxr0qNTfd++rhKbpyiig+Ijl7T4IE/lXqdDIyjV51bV0kqNB5yoqQD/eGQDAEHThtAzIyrqyPaBUwLOUvaEP+u6qA0nWPXFOGgi2vNGAAparvhvkEr9r5o42BHqsvfN7h/W+yy/Z7TZTQVUrxkUOhdst3LjtP+RUCMLs2qt6q3lIFYxwP+cr4ncK/c0xaHwNe3LByy1Iu8Sjm2BOB6id08IZzJCF6irZqp7jvpafOmzMi5RocZdS4OZQuHF3uCG8CUOMXIAU08N+igGqTpWsheblZB1qM2IPkb0kRo16DX9T8Ao+jA/icw9jQ/h8fbdvvwtbE78df50MhZO0yvY8QCKrrn1QljOEC3uRZU0d2K6KlxEgfYtNaz3jYJGje64l7uW4IvFNAlb1a9IGuGGAQ03/FlivuYYA3AwhSwFLWG8zeTH6sv5Z85/kpisbt2jcMbn9mdg8jCwFmg92FBitHK9PbOtHFhqisA347rtukurlhzpDk441jMMIH9l6nt03ps12E4Ann64BsASXVKiRz+xKz2Q==
    DB_USER: AgAVOK7z3Axp4udlmv4TkkQ5kOVt3HYEUG+phQ9nt7qpZSYIso3QzvKfT8moTm+u59mMYJyoIn8iLkx313l6m1rzg0etYPYnDNQ+hd4dVYlC9zN4YGpHR8PplV+wtrivSLZk/DXyAfqkrJe2EcOX3NFyMThK6cjEOgOPt4ziJv9U1bTzuImDDGdJKi7uKrlDrELM9x2VEeDsdrM8JIHkFAcNU0arU67zebtwdfQ1OIPbG5hQZQCNnmi96GiVSs/hKjOzwV4Ebb5pogRVufnu6tA5RLDVB8aBvJJ58PH2+ENOn2rDYOPruq48bCeyUWjkzwd2gFioLx4PvjQSsTxjQ8olmODrvJ7+9ILw7kRSwUZlyKw4/jbY2nXlLXYoXi50Yvm6EDkgbGPJ2r53etPwyMAgAT0VIk4MF/5ouAuSjICld1c3TxAO+7dISpK6dcAPtz3ifefx7cmLEO0saXqrCVb4XcC3zZKEfg5cSG3VIZqkMi+E95RmskjtCgADrAorUAzb7MPmTAi3WDVrwhqA56dPGS3ocxcIOvS8gT5/LzYekJ/qKvA4+gw4smdY2tZHJ0AVZYjSiOtCmPeOpI4B1JgQYL9Kdk+J1qwcqvAEjop68TjaCertVB/7lJ2Zo2sOETZYfwbcEGTbS3LiymvXatCt3kQdk98hmSoUfNqVYPiIooHnHmqnebDddI0ycJKaPekhlCPpJ8PEbQ==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: b2b-db-secret
      namespace: b2bi-prod
    type: Opaque

